'use strict';
/**
 * page-laws.cjs — Z-30 MOBILE-STEWARD DESK (static mobile-law checker for public pages).
 *
 * Operator msg 26: pages must hold at 390px, menus must actually close, tables must
 * scroll, professional design. This desk makes those LAWS machine-checkable in CI:
 *   LAW-1  viewport meta present;
 *   LAW-2  design-system wave marker present (Z-29-a polish, 44px targets);
 *   LAW-3  table scroll wrapper (.tblscroll or overflow-x handling) where tables exist;
 *   LAW-4  menu close law (hashchange / route-close / link-tap delegation) present;
 *   LAW-5  no forbidden-viewport killer (body fixed width) — heuristic: no `width: 10xxpx` on body/html.
 * Fail-soft, keyless, exit 0.
 */
const fs = require('fs');
const path = require('path');
const https = require('https');

const OUT_JSON = path.join(__dirname, 'page-laws.json');
const OUT_MD = path.join(__dirname, 'page-laws.md');
const RAW = 'https://raw.githubusercontent.com/roshpinacare-sys/';
// Public pages only: Console is the public Pages home; Zip is PRIVATE (raw 404s) —
// its console/wallet.html is byte-synced into Console by weave-console-assets, so
// checking Console/wallet.html checks the published artifact of the Zip canonical.
const PAGES = [
  { repo: 'Console', file: 'index.html' },
  { repo: 'Console', file: 'defi.html' },
  { repo: 'Console', file: 'deposits.html' },
  { repo: 'Console', file: 'money.html' },
  { repo: 'Console', file: 'versus.html' },
  { repo: 'Console', file: 'sovereign.html' },
  { repo: 'Console', file: 'readiness.html' },
  { repo: 'Console', file: 'gate.html' },
  { repo: 'Console', file: 'truth.html' },
  { repo: 'Console', file: 'wallet.html' },
];

const fetchT = (url) => new Promise((res) => {
  const rq = https.get(url, { headers: { 'user-agent': 'fleet-page-laws/1.0' } }, r => {
    if (r.statusCode !== 200) { r.resume(); res(null); return; }  // 404 is NOT content
    let d = ''; r.on('data', c => (d += c)); r.on('end', () => res(d));
  });
  rq.on('error', () => res(null)); rq.setTimeout(20000, () => { rq.destroy(); res(null); });
});

function laws(html) {
  if (!html) return { fetched: false };
  const lower = html.toLowerCase();
  return {
    fetched: true,
    LAW1_viewport: /<meta[^>]+name=["']viewport["']/.test(lower),
    LAW2_designWave: html.includes('Z-29'),
    LAW3_tableScroll: !/<table/.test(lower) || lower.includes('.tblscroll') || lower.includes('overflow-x'),
    // LAW-4 conditional (Z-30 calibration): a page WITH a toggle/burger must carry the
    // close law (hashchange / outside-click / link-tap delegation). A page with only
    // wrapped-links nav has nothing to close — passes with an honest note.
    LAW4_menuClose: !/mburger|menu-toggle|navbar-toggle|hamburger/.test(lower) || /hashchange/.test(html) || /closemenu|menuclose|menu\.classlist\.remove|classlist\.remove\(['"]nav-open/.test(lower),
    LAW5_noFixedBody: !/(<body[^>]+width\s*=\s*["']?\d{4})|(html\s*\{[^}]*width\s*:\s*\d{4}px)/i.test(lower),
  };
}

(async () => {
  const t0 = Date.now();
  const pages = [];
  for (const p of PAGES) {
    const html = await fetchT(RAW + p.repo + '/main/' + p.file);
    const l = laws(html);
    const keys = ['LAW1_viewport', 'LAW2_designWave', 'LAW3_tableScroll', 'LAW4_menuClose', 'LAW5_noFixedBody'];
    const low = String(html || '').toLowerCase();
    const hasToggle = /mburger|[^a-z]burger|menu-toggle|navbar-toggle|hamburger/.test(low);
    const note = (l.fetched && !hasToggle) ? 'no toggle nav (wrapped links) — burger retrofit queued' : '';
    const passed = l.fetched ? keys.filter((k) => l[k]).length : 0;
    pages.push({ ...p, ...l, note, passed, of: keys.length, verdict: !l.fetched ? 'UNREACHABLE' : passed === keys.length ? 'PASS' : 'FAIL' });
  }
  const okAll = pages.every((p) => p.verdict === 'PASS');
  const out = { at: new Date(t0).toISOString(), agent: 'page-laws', allPass: okAll, pages };
  fs.writeFileSync(OUT_JSON, JSON.stringify(out, null, 1));
  const md = [
    '# Page Laws (Z-30 mobile-steward desk)', '',
    'Updated: ' + out.at + ' UTC. Every public page must hold at 390px: viewport, design wave, table scroll, menu close, no fixed body. Browser sweeps remain the gold standard after each UI wave; this desk keeps the laws enforced daily.', '',
    '| page | laws | verdict |',
    '|---|---|---|',
    ...pages.map((p) => '| ' + p.repo + '/' + p.file + ' | ' + p.passed + '/' + p.of + ' | ' + p.verdict + ' |'),
    '',
    okAll ? 'ALL LAWS HOLD.' : 'FAILURES ABOVE — fix before the next UI wave ships.',
    '',
    'Generated by agents/page-laws.cjs.', '',
  ].join('\n');
  fs.writeFileSync(OUT_MD, md);
  console.log(JSON.stringify({ state: 'ok', allPass: okAll }));
  process.exit(0);
})().catch((e) => {
  try { fs.writeFileSync(OUT_JSON, JSON.stringify({ at: new Date().toISOString(), agent: 'page-laws', fatal: String(e.message || e).slice(0, 140) }, null, 1)); } catch (_) {}
  console.log(JSON.stringify({ state: 'fail-soft', msg: String(e.message || e).slice(0, 100) }));
  process.exit(0);
});
