'use strict';
/**
 * workflow-audit.cjs — Z-30 WORKFLOW-PRUNER DESK (twin detection + prune plan).
 *
 * Operator msg 26: "one sovereign body, not layers that talk in different languages".
 * Bootstrap commits spawned 30+ workflows; twins across Console/Domain burn public
 * Actions minutes and muddle authorship. This desk:
 *   1. inventories every workflow in Domain + Console (name, triggers, scripts invoked);
 *   2. detects TWINS (same script-set signature, within a repo or across repos);
 *   3. emits a prune PLAN (dispatch-only tombstone recommendations) — execution happens
 *      in review waves, never blind.
 * Fail-soft, keyless, exit 0.
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const OUT_JSON = path.join(__dirname, 'workflow-audit.json');
const OUT_MD = path.join(__dirname, 'workflow-audit.md');

function inventory(repo) {
  const dir = path.join(ROOT, '..', repo, '.github', 'workflows');
  const out = [];
  let files = [];
  try { files = fs.readdirSync(dir).filter((f) => f.endsWith('.yml') || f.endsWith('.yaml')); } catch (_) { return out; }
  for (const f of files) {
    let txt = '';
    try { txt = fs.readFileSync(path.join(dir, f), 'utf8'); } catch (_) { continue; }
    const name = (txt.match(/^name:\s*(.+)$/m) || [])[1] || f;
    const crons = (txt.match(/cron:\s*'([^']+)'/g) || []).map((s) => s.replace(/cron:\s*'|'/g, ''));
    const scripts = [...new Set((txt.match(/agents\/[\w.-]+\.(cjs|mjs|js)/g) || []))];
    const dispatchOnly = !/schedule:/.test(txt) && /workflow_dispatch/.test(txt);
    out.push({ repo, file: f, name, crons, scripts, dispatchOnly, signature: scripts.slice().sort().join(',') });
  }
  return out;
}

(async () => {
  const all = [...inventory('Domain'), ...inventory('Console')];
  const sig = new Map();
  for (const w of all) {
    if (!w.signature) continue;
    const key = w.repo + '|' + w.signature;
    if (!sig.has(key)) sig.set(key, []);
    sig.get(key).push(w.file);
  }
  const twins = [];
  for (const [key, files] of sig) {
    if (files.length > 1) twins.push({ repo: key.split('|')[0], signature: key.split('|')[1], files });
  }
  const crossRepo = [];
  for (const d of all.filter((w) => w.repo === 'Domain')) {
    for (const c of all.filter((w) => w.repo === 'Console')) {
      const overlap = d.scripts.filter((s) => c.scripts.includes(s));
      if (overlap.length) crossRepo.push({ script: overlap.join(','), domain: d.file, console: c.file });
    }
  }
  const plan = twins.map((t) => ({ keep: t.files[0], tombstone: t.files.slice(1), action: 'set on: workflow_dispatch only (or delete if no history), after one green manual run' }))
    .concat(crossRepo.map((x) => ({ keep: 'Domain/' + x.domain, tombstone: 'Console/' + x.console, action: 'Domain is the execution home; Console copy goes dispatch-only (Console keeps only its Pages-publish duties)' })));
  const out = { at: new Date().toISOString(), agent: 'workflow-audit', count: { domain: all.filter((w) => w.repo === 'Domain').length, console: all.filter((w) => w.repo === 'Console').length }, twins, crossRepoDupes: crossRepo, plan };
  fs.writeFileSync(OUT_JSON, JSON.stringify(out, null, 1));
  const md = [
    '# Workflow Audit (Z-30 workflow-pruner desk)', '',
    'Updated: ' + out.at + ' UTC. Domain workflows: ' + out.count.domain + ' · Console workflows: ' + out.count.console, '',
    '## Twin groups (same script-set, same repo)',
    ...(twins.length ? twins.map((t) => '- `' + t.repo + '`: ' + t.files.join(', ')) : ['- none detected']),
    '',
    '## Cross-repo overlaps (Domain vs Console targeting the same scripts)',
    ...(crossRepo.length ? crossRepo.map((x) => '- ' + x.script + ' → Domain/' + x.domain + ' vs Console/' + x.console) : ['- none detected']),
    '',
    '## Prune plan (execute in review waves, never blind)',
    ...(plan.length ? plan.map((p, i) => (i + 1) + '. KEEP `' + p.keep + '` · TOMBSTONE `' + p.tombstone + '` — ' + p.action) : ['- nothing to prune this run']),
    '',
    'Generated by agents/workflow-audit.cjs.', '',
  ].join('\n');
  fs.writeFileSync(OUT_MD, md);
  console.log(JSON.stringify({ state: 'ok', twins: twins.length, crossRepo: crossRepo.length, planSteps: plan.length }));
  process.exit(0);
})().catch((e) => {
  try { fs.writeFileSync(OUT_JSON, JSON.stringify({ at: new Date().toISOString(), agent: 'workflow-audit', fatal: String(e.message || e).slice(0, 140) }, null, 1)); } catch (_) {}
  console.log(JSON.stringify({ state: 'fail-soft', msg: String(e.message || e).slice(0, 100) }));
  process.exit(0);
});
